### ISSUE TITLE
Validate bom tree

### ISSUE THREAD

**Issue by saiindhu** [aerele/apparelo#25]

**Comment by karthikeyan5** [comment]
Main BOM with all the processes
![image](https://user-images.githubusercontent.com/4847317/71964348-66e8d300-3223-11ea-9db1-9da58225c0f8.png)

BOM for "cutting to packing"
![image](https://user-images.githubusercontent.com/4847317/71964415-8b44af80-3223-11ea-9aa3-97a0d9b84b04.png)

BOM for "stitching to packing" 
![image](https://user-images.githubusercontent.com/4847317/71964438-9697db00-3223-11ea-8010-e9cdb1c2bb09.png)

**Comment by karthikeyan5** [comment]
the BOMS look good
