### ISSUE TITLE
Issues with numeric values in Item Attributes

### ISSUE THREAD

**Issue by Vigneshsekar** [aerele/apparelo#8]
When we have a range of numeric values in the item attributes, it is not showing up in the UI.

For example, we made dia to start from 28 to 42 incrementing 0.25.

Earlier, we assumed it to be a front-end issue. But after trying to use a similar functionality, the issue arises from a helper function likely also used by the front-end.

`get_attribute_values` in `item_variant.py` doesn't return numeric values for me.

Moving forward, we shall go with data values for all the item attributes. 

Let's debug and resolve the issue and modify our code later. @karthikeyan5, suggestions?

**Comment by karthikeyan5** [comment]
to fix this we need to add the `add_fetch` function from js to python. quick fix would be to add `numeric_values: 1` in attrribute child table.
